import express from 'express';
import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import cookieParser from 'cookie-parser'; import path from 'node:path';
import { env } from './config/env.js'; import { ensureWorkbook } from './services/spreadsheet.service.js'; import { seedAdmin } from './controllers/auth.controller.js';
import authRoutes from './routes/auth.routes.js'; import productRoutes from './routes/product.routes.js'; import orderRoutes from './routes/order.routes.js'; import userRoutes from './routes/user.routes.js'; import adminRoutes from './routes/admin.routes.js'; import { errorHandler } from './middleware/error-handler.js';
const allowedOrigins = [...new Set([env.clientUrl, 'http://localhost:5173'].flatMap(value => value.split(',').map(origin => origin.trim().replace(/\/+$/, '')).filter(Boolean)))];
const corsOptions = { origin: (origin, callback) => callback(null, !origin || allowedOrigins.includes(origin)), credentials: true, methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], allowedHeaders: ['Content-Type', 'Authorization'] };
const app=express(); app.set('trust proxy', 1); app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}})); app.use(cors(corsOptions)); app.options('*', cors(corsOptions)); app.use(rateLimit({windowMs:15*60*1000,max:300})); app.use(express.json({limit:'1mb'})); app.use(cookieParser()); app.use('/uploads',express.static(path.resolve(env.uploadDir)));
app.get('/api/health',(req,res)=>res.json({success:true,message:'M3NACE Store API is running'})); app.use('/api/auth',authRoutes); app.use('/api/products',productRoutes); app.use('/api/orders',orderRoutes); app.use('/api/users',userRoutes); app.use('/api/admin',adminRoutes); app.use(errorHandler);
for(const type of ['products','users','orders']) await ensureWorkbook(type); await seedAdmin(); app.listen(env.port,()=>console.log(`M3NACE Store API listening on http://localhost:${env.port}`));
